# SLR Summary {#SLRSummary}

The following is a process for fitting a simple linear regression model. Consider this process as you learn to fit simple linear regression models, but don't consider this to be a concrete process for all models.

1. Perform a thorough EDA. Pay close attention to the form, strength, and outliers on the scatterplot of the response and explanatory variables.
1. Show the overall sample size.
1. Address the independence assumption.
1. Fit the untransformed full model with `lm()`.
1. Check the other four assumptions for the untransformed model with `assumptionCheck()`. 
    * Check the linearity of the relationship a residual plot.
    * Check homoscedasticity with the residual plot.
    * Check normality of residuals with an Anderson-Darling test and histogram of residuals.
    * Check outliers and influential points with the outlier test and residual plot.
1. If an assumption or assumptions are violated, then attempt to find a transformation where the assumptions are met.
    * Use trial-and-error with `assumptionCheck()`, theory (e.g., power or exponential functions), or experience to identify possible transformations for the response variable and, possibly, for the explanatory variable.
    * If only an outlier or influential observation exists (i.e., linear, homoscedastic, and normal residuals) and no transformation corrects the "problem", then consider removing that observation from the data set.
    * Fit the full model with the transformed variable(s) or reduced data set.
1. Construct an ANOVA table for the full model `anova()` and interpret the overall F-test.
1. Summarize findings with coefficient results and confidence intervals with `cbind(coef(),confint())`.
1. Create a summary graphic of the fitted line with 95% confidence band using `ggplot()`.
1. Make predictions if desired with `predict()`.

&nbsp;

## Climate Change Data

Climate researchers examined the relationship between global temperature anomaly and the concentration of CO<sub>2</sub> in the atmosphere. Temperature anomaly data was recorded as the Global Land-Ocean Temperature Index from the Goddard Institute of Space Studies (GISTEMP). It is reported in units of 1/100<sup>C</sup> increase above the 1950-1980 mean. The CO<sub>2</sub> data are from The Earth System Research Laboratory of the National Oceanic and Atmospheric Administration (NOAA). Specifically, these data are a record of annual mean atmospheric CO2 concentration at Mauna Loa Observatory, Hawaii, and constitute the longest continuous record of atmospheric CO<sub>2</sub> concentration. This remote location at high altitude in Hawaii was chosen because it is relatively unaffected by any local emissions and so is representative of the global concentration of a well-mixed gas like CO<sub>2</sub>. These observations were started by C. David Keeling of the Scripps Institution of Oceanography in March of 1958 and are often referred to as the Keeling Curve. Data are reported as a dry mole fraction defined as the number of molecules of carbon dioxide divided by the number of molecules of dry air multiplied by one million (ppm). Our goal here is to determine if the variability in the temperature anomaly records can be reasonably explained by the CO<sub>2</sub> values in the same year.

```{r}
cc <- read.csv("http://derekogle.com/NCMTH107/modules/CE/GSI_data.csv")
```


#### R Code and Results {-}

&nbsp;


## Forest Allometrics

#### R Code and Results {-}
