--- 
lang: "en"
title: "Readings for MTH207"
author: "Derek H. Ogle"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
url: 'http\://derekogle.com/Book207/'
github-repo: droglenc/Book207
description: "This book contains the readings for MTH207 at Northland College."
---

# Preface {-}

**This BOOK-IN-PROGRESS was last updated on: `r format (Sys.Date(), '%d %b %Y')`**.

```{r setup, include=FALSE}
library(NCStats)
library(ggplot2)
library(patchwork)
library(emmeans)
knitr::opts_chunk$set(comment="#R>  ",message=FALSE,warning=FALSE,
                      fig.align='center',fig.width=3.5,fig.height=3.5)
options(show.signif.stars=FALSE,knitr.kable.NA = '')
clrs <- c("#1dabe6","#1c366a","#c3ced0","#e43034","#fc4e51","#af060f")
clrs2 <- clrs[c(1,4)]
clrs3 <- clrs[c(5,2,6)]
lbl_text_size <- 4
khfont <- "Cambria"
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'emmeans', 'ggplot2', 'patchwork'
), 'packages.bib')
```


